### ISSUE TITLE
ReferenceError: [BABEL] /rsg-alt/app/index.js: Unknown option: direct.presets

### ISSUE THREAD

**Issue by mattdell** [theogravity/react-styleguide-generator-alt#11]
Hi, I'm trying to get this library integrated with my project and I'm getting the following error.

```
{
	"name": "rsg/rsg-lib",
	"hostname": "UK134489.local",
	"pid": 15776,
	"level": 50,
	"msg": "[ './~/rsg-alt/app/index.js\\nModule build failed: ReferenceError: [BABEL] /Users/mdell/Work/Repos/web/node_modules/rsg-alt/app/index.js: Unknown option: direct.presets\\n    at Logger.error (/Users/mdell/Work/Repos/web/node_modules/babel-core/lib/transformation/file/logger.js:58:11)\\n    at OptionManager.mergeOptions (/Users/mdell/Work/Repos/web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)\\n    at OptionManager.init (/Users/mdell/Work/Repos/web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)\\n    at File.initOptions (/Users/mdell/Work/Repos/web/node_modules/babel-core/lib/transformation/file/index.js:147:75)\\n    at new File (/Users/mdell/Work/Repos/web/node_modules/babel-core/lib/transformation/file/index.js:137:22)\\n    at Pipeline.transform (/Users/mdell/Work/Repos/web/node_modules/babel-core/lib/transformation/pipeline.js:164:16)\\n    at transpile (/Users/mdell/Work/Repos/web/node_modules/babel-loader/index.js:12:22)\\n    at Object.module.exports (/Users/mdell/Work/Repos/web/node_modules/babel-loader/index.js:71:12)\\n @ multi app' ]",
	"time": "2016-01-16T22:59:18.432Z",
	"v": 0
}
```

Any ideas? Seems Babel related.

**Comment by theogravity** [comment]
I did a google search for `Unknown option: direct.presets`, and the first result seems to address the issue:

https://github.com/babel/babel-loader/issues/132

Hopefully that helps? It seems this comment might be your answer:

https://github.com/babel/babel-loader/issues/132#issuecomment-159471682

Also make sure you're using the right Babel version of rsg (3.x for Babel 6, 2.x for Babel 5).

**Comment by theogravity** [comment]
Found out this is most likely on our end via https://github.com/theogravity/react-styleguide-generator-alt/issues/12. Sorry about that. 

It should now be fixed. The solution involved migrating the `.babelrc` options over to the actual webpack babel loader config

**Comment by mattdell** [comment]
Awesome! Thanks I'll have another look into getting this integrated with my solution. :+1:
