### ISSUE TITLE
CSS loader error

### ISSUE THREAD

**Issue by gregz67** [theogravity/react-styleguide-generator-alt#13]
Really was glad to find this Babel 6 update to this tool!  Hoping to use it.

I've run into a problem where components with a css dependency (e.g. they `require` a css file) fail the `rsp`.  The message says: `Unexpected token .\\nYou may need an appropriate loader to handle this file type`

```
'./src/components/button/css/button.css\\nModule parse failed: /Users/blah/blah/src/components/button/css/button.css Line 1: Unexpected token .\\nYou may need an appropriate loader to handle this file type....'
```

**Comment by theogravity** [comment]
You'll need to add a css loader to your webpack config to parse css files:



```
// postcss-loader / postcss-cssnext is optional i think; provides --webkit/etc bindings in post-processing of css
npm i style-loader postcss-loader postcss-cssnext --save-dev

 webpackConfig: {
            module: {
              loaders: [
                {
                  test: /\.css$/,
                  loader: 'style-loader!css-loader!postcss-loader',
                  include: [<paths to your css files>]
                }
              ]
            }
          }
```

See:
https://github.com/webpack/style-loader
https://github.com/postcss/postcss-loader

**Comment by theogravity** [comment]
Looks like this was the result of the example `package.json` using `react-styleguide-generator` instead of `rsg-alt`. Thanks for discovering the bug!

If you pull down, blow away the `node_modules` dir in `examples/` and follow the install instructions again, you should be good to go!

**Comment by gregz67** [comment]
Thanks @theogravity!
