### ISSUE TITLE
Fails if input files have no styleguide field

### ISSUE THREAD

**Issue by gregz67** [theogravity/react-styleguide-generator-alt#16]
If any files in the input are missing a `styleguide` field, the styleguide will fail to load.  Error is

`Uncaught TypeError: Cannot read property 'index' of undefined`

Error comes from [contents.js](/theogravity/react-styleguide-generator-alt/blob/master/app/utils/contents.js)

**Comment by theogravity** [comment]
Can probably use `filter()` against `Components` before feeding it into `map()` to filter out the files that lack it. This is completely top of my head. Solution might be more complicated than that. Would welcome a PR.

**Comment by gregz67** [comment]
Yes. I was thinking the same thing regarding filter. I will look into this
tomorrow and submit PR once I find a solution.
