### ISSUE TITLE
Babel plugin to remove styleguide static from components

### ISSUE THREAD

**Issue by NogsMPLS** [theogravity/react-styleguide-generator-alt#18]
Having a babel plugin that could remove the styleguide static for production builds of components would be really nice.

Something like this: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types

Basically, if I'm going to put a static on a component that is only used for docs, and not actually used in my app in production, i would have a way to remove it for minification purposes.

I'll see if I can take a stab at this, but just wanted to bring the idea forward and see if anyone else thought it would be worth looking into.

**Comment by theogravity** [comment]
Totally makes sense! Go for it

**Comment by NogsMPLS** [comment]
WEep, I went ahead and did it:

https://www.npmjs.com/package/babel-plugin-transform-react-remove-statics

This plugin allows you to rip out any statics you want. so it could be proptypes, could be styleguide, whatever. I've tested it on my end and it seems to be working well! Let me know if you have any problems

**Comment by theogravity** [comment]
:+1: I'll update the readme to mention this, thanks!

**Comment by theogravity** [comment]
added

**Comment by gabrielhpugliese** [comment]
Wow awesome! Congrats!

**Comment by NogsMPLS** [comment]
sweet, thanks!

**Comment by lauterry** [comment]
Geat Job ! This issue should be closed, right ?
