### ISSUE TITLE
Passing props for Required PropTypes

### ISSUE THREAD

**Issue by c0** [theogravity/react-styleguide-generator-alt#22]
I have a component that requires a function (`onIncrement`). Is there a way to specify the prop when it's initialized? When there are multiple examples, I can pass in `props` for each, but I didn't see a way to do this when there aren't tabs.

I usually see errors like this:
```
Warning: Failed propType: Required prop `onIncrement` was not specified in `Counter`. Check the render method of `SG.Sections`.
```

**Comment by theogravity** [comment]
Would help to see an example; we do not support a tab-less experience at the moment (PR welcome). The 'Example' tab renders out what you return in `render()`

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/example/components/Features/Additional%20examples%20via%20doc%20comment.js
