### ISSUE TITLE
"Show all" breaks navigation when serving from sub-directory

### ISSUE THREAD

**Issue by samny** [theogravity/react-styleguide-generator-alt#25]
Hello, 

I'm trying out your styleguide generator and I would like to serve a styleguide from a sub-directory called styleguide. I figured out I need to set `"root": "styleguide"` in the styleguide.json. It mostly works fine, except when I click "Show All" the trailing slash in the URL disappears, which breaks any navigation after that.

1. If I'm at the Buttons category (http://localhost:3000/styleguide/#!/Buttons)

2. Then I click "Show All" (http://localhost:3000/styleguide#!.)

3. Then I click the Buttons category again I end up at the root (http://localhost:3000/Buttons)

**Comment by theogravity** [comment]
Can confirm this bug. I'll take a look at it over the weekend, but I'll also welcome a PR (and give contrib / publish rights as well!)

**Comment by samny** [comment]
I had a quick look at this, and found a solution. Not sure it's the best way to solve it, but it works. Here's my fix: https://github.com/theogravity/react-styleguide-generator-alt/pull/27

**Comment by samny** [comment]
Merged and published the fix in #27, version 3.5.1
