### ISSUE TITLE
Proptype documentation not being generated for v2.x?

### ISSUE THREAD

**Issue by ericgio** [theogravity/react-styleguide-generator-alt#26]
We're using the 2.x version because we're still on Babel 5.x. [PropType documentation](https://github.com/theogravity/react-styleguide-generator-alt#additional-examples-via-doc-comment-optional-demo) doesn't seem to be working. Is this a 3.x feature only?

**Comment by theogravity** [comment]
It should work. Using 2.x myself. Can you paste a sample of what you're doing?

**Comment by ericgio** [comment]
Never mind, I got it to work. For the record, here is the working code:
```
const React = require('react');
const Heading = require('components/headings/heading');

/**
 * Top-level heading within the main page content. Subordinate to both
 * `Title` and `Subtitle`.
 */
const HeadingExample = React.createClass({
  displayName: 'HeadingExample',

  propTypes: {
    // Proptypes here
  },

  render() {
    return <Heading>This is a heading</Heading>;
  },
});

HeadingExample.styleguide = {
  category: 'Headings',
  index: '2',
  title: 'Heading',
  code: `<Heading>This is a heading</Heading>`,
};

module.exports = HeadingExample;
```

I was confused because I was trying to handle the proptypes the same way as `styleguide`, eg:
```
HeadingExample.propTypes = {
  // Proptypes here...
};
```

**Comment by theogravity** [comment]
Glad to hear you got it. Closing the issue.
