### ISSUE TITLE
Does Doc comment support all features of static styleguide

### ISSUE THREAD

**Issue by lauterry** [theogravity/react-styleguide-generator-alt#28]
Hello

I'm wondering if Doc comment support all features of static styleguide ? For example, can we use tabs and code snippet with Doc comment ?

Best regards

**Comment by theogravity** [comment]
Whatever https://github.com/reactjs/react-docgen supports, we support since it's what we use internally.

**Comment by lauterry** [comment]
Thank for this precision !

Great job
