### ISSUE TITLE
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client'

### ISSUE THREAD

**Issue by lauterry** [theogravity/react-styleguide-generator-alt#29]
Hello

While running rsg -d to enable webpack, I got this message : 

`Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/lauthierry/workspace/front`

When running http://localhost:3000, I got a empty page.

In the Chome console,  the bundle file content is the same as the index.html

What's wrong ?

**Comment by lauterry** [comment]
This error disappear when I run rsg command line from ./node_modules/rsg-atl/ directory.

I was runnning rsg command from the root of my project.

Still I have an empty page with the following error : 

`vendor.bundle.js:168 Uncaught ReferenceError: _typeof is not defined`

**Comment by theogravity** [comment]
It's really hard to say what's wrong without knowing your environment / how your config / files are set up.

Are you using grunt or gulp to build the files, or are you doing your build using `rsg-alt` from the cli directly?

If you are using `rsg-alt` from the cli directly, it's best to install `rsg-alt` using the global flag as in `npm i rsg-alt -g` to run commands directly. Also note there is a `styleguide.js` file that you must have in your project for it to run properly.

**Comment by lauterry** [comment]
Hello 

I'm using rsg-alt running it from a npm script : 

```
"scripts": {
    "doc": "rsg app/components/WeLove.jsx  -c styleguide.js"
  },
```

Below is my styleguide.js : 

```
var path = require('path');

module.exports = {
    "title": "Perfect React Style Guide",
    files: [
        '../build/style.css'
    ]
};
```

**Comment by theogravity** [comment]
I'm unsure if using a direct file is valid or not, eg

`./rsg app/components/WeLove.jsx -c styleguide.js -dev`

vs

`./rsg app/components/*.jsx -c styleguide.js -dev`

If you look at this line, this is where we're parsing the input for file

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/lib/rsg.js#L62

I've always known it to be a file path, not a specific file, but I could be wrong.

**Comment by lauterry** [comment]
I wanted to retry with *.jsx but got https://github.com/theogravity/react-styleguide-generator-alt/issues/30 :(

**Comment by lauterry** [comment]
Hello 

Since the issue #30 is now closed, I don't have this issue anymore.
