### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by Laiff** [theogravity/react-styleguide-generator-alt#3]
Hello! Did you planing to migrate to babel 6?

**Comment by theogravity** [comment]
Hey there, the webpack support is based off of this project, which says that Babel 6 is not yet supported:

https://github.com/gaearon/react-transform-boilerplate

If you look at their issue list for Babel 6, there's quite a bit to go:

https://github.com/gaearon/babel-plugin-react-transform/pull/50

So until then, Babel 6 support will not be in the RSG.

**Comment by theogravity** [comment]
boilerplate now is babel 6, will look into impl it

**Comment by theogravity** [comment]
@Laiff Support for babel 6 is in, under the `3.x` ver
