### ISSUE TITLE
babelPlugins are ignored?

### ISSUE THREAD

**Issue by FezVrasta** [theogravity/react-styleguide-generator-alt#36]
I have this script to generate the styleguide:

```js
const Generator = require('rsg-alt');

const INPUT = 'app/components/**/*.js';
const OUTPUT = 'docs/styleguide';

var generator = Generator(INPUT, {
    output: OUTPUT,
    config: {
        title: 'SysdigCloud React Style Guide',
        files: [
            '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'
        ],
        babelConfig: {
            presets: ['stage-0', 'react'],
            plugins: [
                'transform-decorators-legacy'
            ]
        }
    }
});
generator.generate();
```

But it complains about the ES6 decorators, even if I'm using the `transform-decorators-legacy`, which works perfectly on my webpack configuration.

Any help?

**Comment by theogravity** [comment]
Looking through `rsg.js`, it seems like we do not use `babelConfig` anymore (it's still used in the original rsg that this project is forked from).

You should set your babel configuration via webpack plugins instead (or `.babelrc` - unsure if it applies or not).

Will update docs and code to remove the `babelConfig` ref.

Sorry about that

**Comment by bendman** [comment]
Is there any way to make it use the babelConfig, rather than always using the .babelrc?  Sometimes it can be useful to have your docs (rsg) run through a different set of loaders than your site.

**Comment by theogravity** [comment]
You should be able to add plugins / override via the `webpackConfig` option.

We basically merge `webpackConfig` into our internal config here:

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/lib/rsg.js#L377

**Comment by bendman** [comment]
@FezVrasta did you ever get it figured out? Updating your config to pass in the babel query param should fix things.  I'd using a config similar to the one below, and ensuring you're on `v3.7.0` or above. 

```javascript
{
    title: "SysdigCloud React Style Guide",
    files: [
        "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
    ],
    webpackConfig: {
        module: {
            loaders: [{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel',
                query: {
                    babelrc: false,
                    presets: ["es2015", "react", "stage-0"],
                    plugins: ["transform-decorators-legacy"]
                }
            }]
        }
    },
}
```

**Comment by FezVrasta** [comment]
No, I'm switching to Carte Blanche to avoid all these problems with webpack configurations.

**Comment by stevoland** [comment]
v3.11.0 has support for a `babelPlugins` option: https://github.com/theogravity/react-styleguide-generator-alt#babelplugins .
