### ISSUE TITLE
pushstate breaks sidebar navigation

### ISSUE THREAD

**Issue by joefraley** [theogravity/react-styleguide-generator-alt#39]
It looks like sidebar navigation using pushstate doesn't work. Navigation just doesn't seem to function at all. You can see this in the official included example styleguide.

1. Open `example/styleguide.json`
2. After line 6, add a line:  `"pushstate": true`
3. `npm run`
4. Navigate to localhost:3000
5. Click any sidebar link, for example "Buttons"  
![](https://www.evernote.com/shard/s495/sh/ccdd5e01-9938-4c70-a53a-fdd88f839808/7626b5ac2f84ce43/res/04e8597e-f945-4c6d-ac64-edd8962a3ad3/skitch.png)
6. Click any other sidebar link, for example "Button dropdowns"  
![](https://www.evernote.com/shard/s495/sh/caf5760d-dd2d-4af0-834b-bb583f0ef6cc/6dff3f2366b986ec.png/res/d9eaa8d9-5994-469d-94e8-b88ec4149178/skitch.png)
7. Repeat.

@bendman and I are starting work on it now. Not sure what the deal is.

**Comment by mattdell** [comment]
I've noticed the same and haven't had a chance to investigate.

**Comment by mattdell** [comment]
Reopining this issue as it needs to be fixed for the v2.x branch as well as v3.x.

**Comment by mattdell** [comment]
I've fixed this for v2.

@joefraley can you fix the component navigation for v3?

**Comment by bendman** [comment]
This was fixed by #47
