### ISSUE TITLE
Support for React-intl

### ISSUE THREAD

**Issue by lauterry** [theogravity/react-styleguide-generator-alt#49]
Hello

My React component use Reac-intl to handle i18n.

For example I have in my component render function : 

```
 <span className="nav__label">
      <FormattedMessage
               id="header.wishlist"
               description='Header - Wishlist menu item'
               defaultMessage="Wishlist"/>
</span>
```

For the ```FormattedMessage``` to work, I need a ```<IntlProvider>```  to exist in the component ancestry.

If not, I got the following error : 

```Uncaught Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.```

How can we solve this use case ?

**Comment by bendman** [comment]
One option I've used in similar situations (unit testing components that are normally dependent on `context`), is to proxy those components through your own file, and serve up a non-context-dependent version, or one with a unit-level context, for certain situations (in your case, when running through RSG)

Example: 

```javascript
// react-intl-proxy.jsx, you would require this instead of the regular `react-intl`
var React = require('react');
var ReactIntl = require('react-intl');

if (__NOCONTEXT__) { // this global variable is set using webpack's `DefinePlugin`
    var ShimmedIntl = Object.assign({}, ReactIntl);

    // Simple mock for FormattedMessage to avoid parsing i18n stuff that depends on context
    ShimmedIntl.FormattedMessage = React.createClass({
        render() { return <span>{this.props.defaultMessage}</span>; }
    });

    module.exports = ShimmedIntl;
} else {
    module.exports = ReactIntl;
}

module.exports = components;
```

Hopefully this makes sense.

**Comment by bendman** [comment]
@lauterry Any luck getting this to work?

**Comment by lauterry** [comment]
Hi @bendman 

I haven't got time to try your proposition yet.

It is in my todolist :)

**Comment by lauterry** [comment]
@bendman 

I've implemented your solution,

It works well.

Thanks

**Comment by wrobel** [comment]
An alternative to this approach (which does not require modification of the original source files and avoids the `__NOCONTEXT__` variable) is to embed the proxy within your webpack configuration for react-styleguide-generator.alt:


    ...
    webpackConfig: {
        resolve: {
            modulesDirectories: ['node_modules', 'scripts'],
            alias: {
                'react-intl': 'styleguide/react-intl-proxy'
            },
            extensions: ['', '.js', '.jsx', '.json']
        },
    ...


I use this with the shim described above within the file `scripts/styleguide/react-intl-proxy.jsx`:

    const React = require('react')
    const ReactIntl = require('react-intl')

    const ShimmedIntl = Object.assign({}, ReactIntl)

    ShimmedIntl.FormattedMessage = React.createClass({
      render() {
        return (
            <span>{this.props.defaultMessage}</span>
        )
      }
    })

    module.exports = ShimmedIntl
