### ISSUE TITLE
document functional components

### ISSUE THREAD

**Issue by lauterry** [theogravity/react-styleguide-generator-alt#53]
Hi

Here is an example of a react functional component : 

```
const Header = ({content}) => {
    return (
        <header className="topbar">
         {content}
        </header>
    );
};
```

Can you tell me if it is possible to document such a component ?

Best regards

**Comment by lauterry** [comment]
Correct me if i'm wrong but I think the answer is no.

As a workaround, I used the same technique mentionned here https://github.com/theogravity/react-styleguide-generator-alt/issues/49#issuecomment-224333530

**Comment by ticemochka** [comment]
For my case, I have pure function components as lauterry, and trying to generate documentation for them, rsg fetches the styleguide and displayName from static data and also propTypes and defaultValues,  but it cannot generate example for such component. Or there is a way?

**Comment by ticemochka** [comment]
example is generated only if the render method is specified
PureFunctionComponent.prototype.render = PureFunctionComponent;

**Comment by theogravity** [comment]
It's probably due to this line:

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/app/components/Sections/index.js#L45

You can probably re-work it to check if the prototype contains render, if not, do x with the component.

Feel free to submit a PR with the fix

**Comment by ticemochka** [comment]
Made a pull request, so I guess this issue can be closed.

**Comment by lauterry** [comment]
Nice @ticemochka
