### ISSUE TITLE
Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.

### ISSUE THREAD

**Issue by mattdell** [theogravity/react-styleguide-generator-alt#54]
I've got this error all of the sudden this morning:

```
Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.
```

I've recently updated my node_modules. Anyone else?

![screen shot 2016-06-21 at 16 52 25](https://cloud.githubusercontent.com/assets/2536442/16236930/075a9e2c-37d2-11e6-8023-d47662fdbfa7.png)

**Comment by mattdell** [comment]
This happened because redbox-react has been updated. It is now on 1.2.9 and the most recent working version for me is 1.2.6. Updating to 1.2.7 produces the same error.

I would suggest updating the package.json from `"redbox-react": "^1.2.0"` to `"redbox-react": "1.2.6"`

**Comment by theogravity** [comment]
Ah. Yeah we should definitely just fix the versions
