### ISSUE TITLE
Importing webpack config file giving unhelpful Webpack error

### ISSUE THREAD

**Issue by i-a-n** [theogravity/react-styleguide-generator-alt#61]
I'm attempting to import a webpack config file that's already working with our webpack server, but when building rsg-alt, it fails. Here is my config file:

```js
const webpackConfigFile = require('./internals/webpack/webpack.dev.babel');

module.exports = {
	title: '$TITLE',
	reactDocgen: {
		files: ['app/components/*/index.js']
	},
	webpackConfig: webpackConfigFile
};
```

And here's the error when runing `rsg`:

```json
{
    "name": "rsg/rsg-lib",
    "hostname": "MacBook-Pro-2.local",
    "pid": 67971,
    "level": 50,
    "err": {
        "message": "request.replace is not a function",
        "name": "TypeError",
        "stack": "TypeError: request.replace is not a function
		    at $PATH/node_modules/rsg-alt/node_modules/webpack/lib/NormalModuleFactory.js:72:27
		    at $PATH/node_modules/rsg-alt/node_modules/webpack/lib/NormalModuleFactory.js:28:4
		    at handleExternal ($PATH/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:25:32)
		    at $PATH/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:81:24
		    at handleExternals ($PATH/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:78:5)
		    at ExternalModuleFactoryPlugin.<anonymous> ($PATH/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:79:5)
		    at $PATH/node_modules/rsg-alt/node_modules/webpack/lib/NormalModuleFactory.js:159:3
		    at NormalModuleFactory.applyPluginsAsyncWaterfall ($PATH/node_modules/tapable/lib/Tapable.js:75:69)
		    at NormalModuleFactory.create ($PATH/node_modules/rsg-alt/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
		    at $PATH/node_modules/rsg-alt/node_modules/webpack/lib/Compilation.js:214:11
		    at $PATH/node_modules/async/lib/async.js:181:20
		    at Object.async.forEachOf.async.eachOf ($PATH/node_modules/async/lib/async.js:233:13)
		    at Object.async.forEach.async.each ($PATH/node_modules/async/lib/async.js:209:22)
		    at Compilation.addModuleDependencies ($PATH/node_modules/rsg-alt/node_modules/webpack/lib/Compilation.js:185:8)
		    at Compilation.processModuleDependencies ($PATH/node_modules/rsg-alt/node_modules/webpack/lib/Compilation.js:170:7)
		    at Compilation.moduleReady ($PATH/node_modules/rsg-alt/node_modules/webpack/lib/Compilation.js:412:9)"
    },
    "msg": "request.replace is not a function",
    "time": "2016-07-07T20:37:30.911Z",
    "v": 0
}
```

Checking online, there's not much information about this error. The common theme is that the config object's structure is not what webpack expects.

Now, my first guess was that my project's webpack version was higher than rsg-alt's (it is), so perhaps there was an update to the webpack config object structure. However I updated the webpack version locally and (after a few unrelated issues), the same error emerges.

Has anyone encountered this before? Or, have any ideas on how to find what about my config file rsg's webpack setup doesn't like?

**Comment by theogravity** [comment]
It's unfortunately hard to say without knowing what your webpack config looks like. You're also welcome to submit a pr to update the webpack items

**Comment by grammka** [comment]
@i-a-n check this https://www.garysieling.com/blog/fixing-webpack-error-typeerror-request-replace-not-function

**Comment by i-a-n** [comment]
Thanks for the reply! I'll try to find where the mismatch is coming from and if there's a fix I can apply to the webpack setup here I'll submit a PR.

If it's okay with you I'd like to leave this issue open for a few days in case anyone else has encountered it. I'll close it when I get it working one way or the other. Thanks!

**Comment by bendman** [comment]
Bunyan certainly isn't helping, as it's outputting what would normally be legible errors and a stack trace as a JSON object in a big string.

**Comment by theogravity** [comment]
I'm okay with removing bunyan in favor of `debug` instead

**Comment by bendman** [comment]
Since there doesn't seem to be a configuration for RSG's logging, what benefit would a logger like `bunyan` or `debug` provide over the native `console` methods?

**Comment by theogravity** [comment]
Because some build systems will want logging in specific formats, like json

**Comment by fenos** [comment]
I've got the exactly the same issue, with the same stack trace. Any news on this?

**Comment by theogravity** [comment]
None, but always open to PRs for it

**Comment by fenos** [comment]
Ok, i will be happy to contribute, however the error doesn't tell much, so I'll try to remove each loader/plugin one by one to see if I can find the cause of it

**Comment by theogravity** [comment]
Sorry about that :(

**Comment by i-a-n** [comment]
@fenos Sorry I don't have much help to give: I narrowed down that the error only happened after I included my `app.js` as an `entry` in the config file. My `app.js` has like five hundred other things it does, none of which were relevant to `rsg-alt`, so instead of finding which one broke everything, I just duplicated my webpack config and removed everything that wasn't relevant to building a style guide. So I have a special webpack config file now just for `rsg-alt` which isn't perfect, but at least it works.

Good luck.

**Comment by theogravity** [comment]
Thanks for looking into it, @i-a-n. Was your `entry` being set as an array or an object?

**Comment by i-a-n** [comment]
@theogravity Array. It looked something like this, I believe: 
```js
entry: [
		'eventsource-polyfill',
		'webpack-hot-middleware/client',
		path.join(process.cwd(), 'app/app.js')
	],
```

I seem to recall that just removing the last item fixed the problem. But I can't quite remember because this was almost three weeks ago and that might as well have been three years ago in developer-time.

**Comment by theogravity** [comment]
I think that might be the problem. If you look at the rsg `entry` prop, it's not an array:

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/lib/rsg.js#L325

https://webpack.github.io/docs/configuration.html

According to the webpack docs, either is valid. Unsure right now what the right fix would be - using an array vs object has different use cases depending on the project. Open to suggestions.

**Comment by fenos** [comment]
@theogravity yes! that what exactly the issue, to fix that i did as following (it should work either with object or array as entry value)

```js
var entry = [];
if (Array.isArray(this.opts.webpackConfig.entry)) {
  entry = this.opts.webpackConfig.entry;
  delete this.opts.webpackConfig.entry;
}

return deepmerge({
    entry: {
      app: [path.resolve(__dirname, '../app/index.js')].concat(self.opts.dev ? [
        'webpack-hot-middleware/client'
      ] : []).concat(entry)
    },
```
What do you think?

**Comment by theogravity** [comment]
How would it work if the incoming config was an object? Is it necessary to delete `entry` from the user's webpack config?

**Comment by fenos** [comment]
Would not deepmerge take care of merging the object into entry?

**Comment by theogravity** [comment]
touche, you are correct

**Comment by i-a-n** [comment]
Thanks everyone!!
