### ISSUE TITLE
Using React 15.3.x: rsg-alt works fine, but react-simpletabs breaks NPM

### ISSUE THREAD

**Issue by i-a-n** [theogravity/react-styleguide-generator-alt#69]
So I'm using react@15.3.0 in my parent project, and rsg-alt is working without a problem as a dependency, but NPM is choking on one of the peerDependencies specified in an rsg-alt dependency. It's called react-simpletabs:

```
"react-simpletabs": "github:matthewgertner/react-simpletabs",
```

react-simpletabs' package.json has this line:

```
  "peerDependencies": {
    "react": "0.12.x - 1.x"
  },
```

Since that version of react isn't what I'm installing, and it's also not in the react-simpletabs dependencies, it doesn't install it, and I'm getting a non-fatal NPM error when installing (and a fatal NPM error when doing other tasks such as shrinkwrapping).

Do you have any solutions immediately come to mind? I have a feeling react-simpletabs will work with react@15.x, so perhaps I could just fork react-simpletabs and remove the peer dependency, test it, and update rsg-alt to use the forked one. Or, since it's only two smallish files, maybe we could pull it into rsg-alt, if tabs are a vital part of rsg-alt's experience. Or, I could just fork rsg-alt for myself and leave out react-simpletabs. Lot of options.

Any suggestions how to best proceed? This will be a pretty big problem once more and more people use react@15.x I'm guessing.

**Comment by theogravity** [comment]
So the use of this custom repo was the result of https://github.com/pedronauck/react-simpletabs/issues/26

I think it's safe at this point to fork that repo and publish an alternative version with the proper react updates

I have a feeling it should work as well

**Comment by i-a-n** [comment]
Sounds good, I'll work on that this week.
