### ISSUE TITLE
webpackConfig config example

### ISSUE THREAD

**Issue by AlexEOL** [theogravity/react-styleguide-generator-alt#8]
I already have written webpack.config.js file. How can I integrate it here?

**Comment by CosticaPuntaru** [comment]
+1

**Comment by theogravity** [comment]
I have been feeding the options via `grunt`, but just pushed an update now where you can specify a JS config file directly.

See:
https://github.com/theogravity/react-styleguide-generator-alt#command-line-tool
https://github.com/theogravity/react-styleguide-generator-alt#config

**Comment by lauterry** [comment]
Hello

I can't figure out how to integrate react-styleguide-generator-alt with webpack.

Can you provide an example and add it to the readme please ?

Best regards

**Comment by lauterry** [comment]
Ok, I found out in the readme. Sorry for the noise
