### ISSUE TITLE
Generate Description & Prop from Component File

### ISSUE THREAD

**Issue by danielduan** [theogravity/react-styleguide-generator-alt#83]
I don't see a way to run react-docgen on the actual component file.

It seems more logical that the documentation lives on the component file itself, and not in an external used only for generating this style guide.

Maybe we can have something in the rsg component to specify the option of running it on the actual file instead of the rsg component.

**Comment by goodmorninggoaway** [comment]
Check out babel-plugin-react-docgen.

**Comment by danielduan** [comment]
Thanks for that. Wish it was more closely integrated. Decided to go with `@kadira/storybook` for instead.
